name: movie_catalog_app
description: A Flutter application to browse movies using TMDB API.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cached_network_image: ^3.2.1

flutter:
  uses-material-design: true
